version: '2'

services:

  bluetooth:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
    environment:
      BLUETOOTH_RECONNECT_WAIT: 10

  audio:
      image: balenablocks/audio:raspberrypi4-64  # See supported devices for other archs
      privileged: true
      labels:
        io.balena.features.dbus: 1  # Only required for bluetooth support
      ports:
        - 4317:4317                 # Only required if using PA over TCP socket