version: '2'

services:

  bluetooth:
    build: .                        # See supported devices for supported archs
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1